### ISSUE TITLE
Doesn't work for Contra

### ISSUE THREAD

**Issue by adambarta** [AndreaOrru/LaiNES#15]
?

**Comment by AndreaOrru** [comment]
Read the README. Contra uses Mapper 002, it's not currently implemented. Shouldn't be too hard to add support. Contributions are welcome :)

**Comment by johnrocamora** [comment]
@AndreaOrru I think the same can be said for BattleToads, I'll check later to make sure. Awesome project, btw!

**Comment by AndreaOrru** [comment]
Thanks! All the interest is really motivating for me to keep improving this. BattleToads is the ultimate accuracy beast, I'm expecting some extra fixes will be needed to make it work.

**Comment by kraln** [comment]
I'll have a look at Mapper 002, and whatever BattleToads uses--see if I can't contribute

**Comment by kraln** [comment]
Should be solved by https://github.com/AndreaOrru/LaiNES/pull/16 -- note that this exposes some other issues (Castlevania and Contra both have graphical issues, but load and play). I think these issues aren't mapper problems...

**Comment by AndreaOrru** [comment]
Thanks @kraln, there are various reasons I can think of why there would be graphical problems. 

There is a list of issues I wrote 3 years ago and those are good candidates to work on in order to improve accuracy. It all feels kind of weird to me 'cause this unknown thing I built back in uni is now at the center of attention and suddenly worth of love :)

**Comment by kraln** [comment]
hackernews is weird like that. I'm going to work through some of the to-do list... if you're still willing to moderate the project I'm willing to put some effort in. consider accepting the PR(s) and I can see what else can be done to get contra going?

**Comment by AndreaOrru** [comment]
Yeah I'm definitely willing to put some effort on this. Thanks for your contributions. :)

**Comment by johnrocamora** [comment]
I'm guessing that it's because it's concise and uses C++11. A lot of us work/worked on projects that for some reason or other don't/didn't allow us to use modern C++ features (not even boost!), so this is eye candy :)

**Comment by johnrocamora** [comment]
That and the NES Classic Edition coming out soon and currently being sold out

**Comment by kraln** [comment]
Just a note, Castlevania, Duck Tales and Duck Tales 2 seem to have similar issues. Contra is especially broken. Commando seems just fine.

**Comment by AndreaOrru** [comment]
Ok. Are those all mapper 002? There may be something there. Actually Castlevania not loading the background sounds a lot like a mapper problem.

**Comment by kraln** [comment]
Yes, those are all mapper 002. Mapper 002 has mirroring hard-wired on the cart, so my implementation reads the iNES header to set the mirroring. Is mirroring not fully implemented? I will dig in, then.

**Comment by kraln** [comment]
Ah, I am reading the wrong header byte. When I read the correct header byte, the aforementioned games work.

**Comment by kraln** [comment]
#18 should resolve.

**Comment by adambarta** [comment]
Nice! thanks

**Comment by AndreaOrru** [comment]
Great work @kraln. Maybe I should write an internal debugger for this stuff.

**Comment by kraln** [comment]
@johnrocamora battletoads has partial support as of #28, but seems to be particularly nasty to emulate
