### ISSUE TITLE
libretro support

### ISSUE THREAD

**Issue by AndreaOrru** [AndreaOrru/LaiNES#22]
This has been proposed on /r/emulation and Hacker News. I think there would be a lot of value in it. Prioritize.

**Comment by kraln** [comment]
I guess the question is, what niche or purpose is LaiNES? Is it an easy-to-grok, clean, accurate open-source c++ NES Emulator? Libretro already has two NES emulators--what's the differentiation there?

**Comment by AndreaOrru** [comment]
I agree the main focus of LaiNES shouldn't be mainstream adoption - that place is already taken by at least a couple of other good emulators. I guess evaluating how much work integrating libretro actually involves would help taking a decision though. I bet it would end up being less code than the current GUI, overall. On the other hand, it wouldn't be as customizable if we wanted to add, say, a debugger.

I think there is more value in making this codebase accurate, while at the same time keeping it compact and readable, sort of a good starting point to understand how a NES works. Decoupling the core from the extra features as much as possible, and then having an optional compilation flag for debugging purposes. 

Awesome debugging capabilities are what could set this apart from the rest, in fact. That's pretty exciting.
