### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by AndreaOrru** [AndreaOrru/LaiNES#23]
Pretty tired of having to reconfigure the joystick every time I open this :)

**Comment by kraln** [comment]
so far, it's screen size and joystick. would also like to consider making some other things (sound sampling rate?) configurable.

Do you think flatfile (ini? https://github.com/benhoyt/inih?), json, sqlite, etc?

**Comment by AndreaOrru** [comment]
Yeah sure, the more the merrier.

A simple ini format will suffice. Inih looks really nice, but C++ dependencies are a real pain. Probably better to write a simple parser in house. :)

**Comment by kraln** [comment]
https://arxiv.org/pdf/1103.3021.pdf?origin=publication_detail for existing stuff

**Comment by kraln** [comment]
Resolved with #25, right? :)
