### ISSUE TITLE
2562edf major regression (crashes, etc).

### ISSUE THREAD

**Issue by kraln** [AndreaOrru/LaiNES#24]
The directory re-org seems to have broken several games

**Comment by kraln** [comment]
Tested: Castlevania 2 (doesn't boot anymore), Contra (freezes in demo)

**Comment by kraln** [comment]
Git bisect:

2562edfe9a139842a4b563b1b5c7a6c49a98e605 is the first bad commit
commit 2562edfe9a139842a4b563b1b5c7a6c49a98e605
Author: Andrea Orru <andreaorru1991@gmail.com>
Date:   Thu Dec 1 18:46:38 2016 -0500

    Reorganized directory structure.

:100644 100644 251993122a055277a3ab9ef7d95b258acc4cfbd8 155760c596b8095f9375ee440a52bdbc15eae51d M	README.md
:100644 100644 d9b6582b32855f51b5cd45fa70e8e93b71c98a81 2e28935a32c5939b2a859efe29c43aba5920722a M	SConstruct
:040000 000000 9c15fcc7e2cf1fa19efc334c900b6b1580a8550c 0000000000000000000000000000000000000000 D	img
:000000 040000 0000000000000000000000000000000000000000 be5165bc886f71ce32f4a881e53d76e6b6c0fa3c A	lib
:040000 040000 94be6fe794880bef10ef5cb94f16c5314d1dca61 21bd794c55879b972140c560a3ff993eaf9fb86d M	src

**Comment by AndreaOrru** [comment]
Solved. Link-time optimizations were the issue. Thanks for reporting this.

We really need tests. I'll work on that next.
