### ISSUE TITLE
Invalid instruction? Puzznic causes exit(1)

### ISSUE THREAD

**Issue by kraln** [AndreaOrru/LaiNES#26]
Starting a game of puzznic, when you move a piece, LaiNES exits with code 1. Invalid opcode?

**Comment by AndreaOrru** [comment]
Probably. Have you tried changing the invalid opcode case with a printf?

**Comment by kraln** [comment]
Seems to be a handful of "invalid" opcodes which do useful things, and were used in a handful of real games (many may be porting errors) and in some homebrew as well. #29 fixes the ones that used NOPs, anything more exotic will be broken unless we implement the remaining invalid opcodes.
