### ISSUE TITLE
Fast Execution

### ISSUE THREAD

**Issue by Kautenja** [AndreaOrru/LaiNES#35]
Is it possible to modify this code to remove all frame limiting mechanisms? For instance, if I wanted to adapt this library to allow a machine learning algorithm to process game data at something close to 1000 frames per second (rough number), would that be doable?

Removing the frame limiting mechanism in the run function of the GUI appears to provide some speedup, but are there other modifications to potentially boost this further?

**Comment by Kautenja** [comment]
Figured it out. Removing the frameskip logic, all APU functionality, and increasing `TOTAL_CYCLES` in the CPU will increase the speed to where I need it to be. Closing the issue.

**Comment by AndreaOrru** [comment]
:+1:
