### ISSUE TITLE
cycle number of Instructions

### ISSUE THREAD

**Issue by mmmmar** [AndreaOrru/LaiNES#36]
I find cycles of instruction don't match the information is list [here](http://nesdev.com/6502.txt).
for example:
```
ADC<imm>() :
inline u8  rd(u16 a)            { T; return access<0>(a);      }
#define G  u16 a = m(); u8 p = rd(a) 
inline u16 imm()   { return PC++;                                       }
template<Mode m> void ADC() { G       ; s16 r = A + p + P[C]; upd_cv(A, p, r); upd_nz(A = r); }
```
it only ticks once, but in that link this ins need two cycles 
```
 +----------------+-----------------------+---------+---------+----------+
  | Addressing Mode| Assembly Language Form| OP CODE |No. Bytes|No. Cycles|
  +----------------+-----------------------+---------+---------+----------+
  |  Immediate     |   ADC #Oper           |    69   |    2    |    2     |
```

**Comment by AndreaOrru** [comment]
Hi, I realize I'm not super responsive - unfortunately I don't have a lot of time to dedicate to this project anymore (although I would like to in the future).

Why did you close the issue? Did you realize it actually ticks twice? :D Genuine question.

**Comment by mmmmar** [comment]
```
void exec()
{
    switch (rd(PC++))  // Fetch the opcode.
    { 
      ....
    }
}
```
when fetch the opcode, it ticks first.
so your implementation is right.
