### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by xem** [AndreaOrru/LaiNES#43]
Hello,
I didn't manage to build the project on Ubuntu
More precisely, "scons" provokes 404 errors
![image](https://user-images.githubusercontent.com/1225909/124245986-cb3ad900-db20-11eb-98ed-ee2f1a810114.png)
Any idea how to fix?
Can you please provide a build executable for people who have the same issue?
Thanks!

**Comment by kraln** [comment]
It looks like your package manager is out of date. Try to update it (sudo apt-get update) before installing scons.

**Comment by xem** [comment]
ah yes it works! thanks :)
